### ISSUE TITLE
When installing a language laravel breeze is not detected

### ISSUE THREAD

**Issue by luisprmat** [andrey-helldar/laravel-lang-publisher#115]
- Lang Publisher Version: 10.0.1
- Laravel Version: 8.43.0
- PHP Version: 8.0.3

### Description:
This program don't translate laravel breeze keys.
If i want use **laravel breeze** instead _laravel jetstream_ (with fortify), the keys aren't translated

### Steps To Reproduce:
- Install a new laravel project `laravel new my-project`
- `cd my-project`
- Install laravel breeze `composer require laravel/breeze --dev`
- run breeze command `php artisan breeze:install`, then `npm install`, `npm run dev`, `php artisan migrate`.
- install **lang-publisher** `composer require andrey-helldar/laravel-lang-publisher --dev`
- Set some language, for example spanish `php artisan lang:add es`
- Set locale to `es` in `config/app.php`
- Go to route `register` for example (This view is not translate)

i guess laravel breeze uses translations from laravel jestream and that's the reason why it doesn't work.

**Comment by andrey-helldar** [comment]
I will check shortly what translations it uses and either add its definition to jetstream files (or other product) or send a PR to the `laravel-lang/lang` repository.

**Comment by andrey-helldar** [comment]
One of the keys is in the fortify project.

I will prepare and submit a PR to add a file for the `laravel/breeze` project in `laravel-lang/lang` and implement support for this file in this package.

![image](https://user-images.githubusercontent.com/10347617/119805285-c9f70a80-bee9-11eb-8564-89cda0188c76.png)

**Comment by andrey-helldar** [comment]
PR in this project: #116
Wait for https://github.com/Laravel-Lang/lang/pull/1763

**Comment by andrey-helldar** [comment]
@luisprmat, as a workaround, added detection of the installed Breeze package and copying keys from jetstream and fortify.

Released in [v10.0.2](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v10.0.2)
