### ISSUE TITLE
Keys inside attributes array removed when update

### ISSUE THREAD

**Issue by mohamedsabil83** [andrey-helldar/laravel-lang-publisher#126]
- Lang Publisher Version: 10.0.4
- Laravel Version: 8.45.1
- PHP Version: 8.0.7

### Description:
When run `php artisan lang:update` all keys within **attributes** array removed for all locales but **en**.

### Steps To Reproduce:
- install any locale.
- add translation keys within **attributes** array.
- run 'php artisan lang:update'.

**Comment by andrey-helldar** [comment]
At the moment there are some problems with version 10. I will fix them shortly.

https://github.com/andrey-helldar/laravel-lang-publisher/pull/123

**Comment by andrey-helldar** [comment]
@mohamedsabil83, i released version [`10.1`](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v10.1.0). Can you update and check?

**Comment by mohamedsabil83** [comment]
Sure, I'll check it and notify you

**Comment by andrey-helldar** [comment]
Thank you!

I found a few more bugs and are now fixing them.

**Comment by audunru** [comment]
Just install 10.1.4 and I don't have this problem anymore @andrey-helldar . keys/values inside the attribues array in my non-english language files are still there.

**Comment by mohamedsabil83** [comment]
I'll try v10.1.4 today. Yesterday, I tried v10.1.3 and the Arabic files return empty array.

**Comment by andrey-helldar** [comment]
> Just installed 10.1.4 and I don't have this problem anymore @andrey-helldar . keys/values inside the attribues array in my non-english language files are still there.
> 
> edit: typos

You can invoke the reset command:

`php artisan lang:reset --full`

It will remove all unnecessary keys.

**Comment by andrey-helldar** [comment]
> I'll try v10.1.4 today. Yesterday, I tried v10.1.3 and the Arabic files return empty array.

Yes, that was one of the errors I found. I fixed it in 10.1.4.

**Comment by andrey-helldar** [comment]
@mohamedsabil83, I know what is the reason :)

The publisher takes the list of keys from the original. Since your application does not have keys, it will not add them.

And I know how to solve this problem :)

**Comment by andrey-helldar** [comment]
@mohamedsabil83, I have submitted a solution to this problem to the main repository: https://github.com/Laravel-Lang/lang/pull/1861
