### ISSUE TITLE
Non-English files returned an empty array + json files not imported

### ISSUE THREAD

**Issue by mohamedsabil83** [andrey-helldar/laravel-lang-publisher#150]
- Lang Publisher Version: 10.1.5
- Laravel Version: 8.61.0
- PHP Version: 8.0.10

### Description:
Added locales files return an empty array and related JSON files not imported.

**EN**
![Screenshot from 2021-09-26 12-15-14](https://user-images.githubusercontent.com/10126040/134801700-287d84a7-2bf9-46f9-bde9-34ce6f73ceb3.png)

**AR**
![Screenshot from 2021-09-26 12-15-42](https://user-images.githubusercontent.com/10126040/134801614-44dfd2b0-babd-4d4c-af05-e3de2779aace.png)

**FR**
![Screenshot from 2021-09-26 12-15-29](https://user-images.githubusercontent.com/10126040/134801607-db438c77-fa1c-42db-a33a-0dc123df5fb1.png)

**Comment by andrey-helldar** [comment]
Thank you!

Fixed bug in version [`10.1.6`](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v10.1.6) (released)
