### ISSUE TITLE
Problem Installing package for L5.7

### ISSUE THREAD

**Issue by jhm-ciberman** [andrey-helldar/laravel-lang-publisher#4]
I don't quite understant what I am doing wrong.
**Laravel Framework 5.7.28**

```
vagrant@homestead:~/code/ce$ composer require andrey-helldar/laravel-lang-publisher --dev
Using version ^1.2 for andrey-helldar/laravel-lang-publisher
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for andrey-helldar/laravel-lang-publisher ^1.2 -> satisfiable by andrey-helldar/laravel-lang
-publisher[v1.2.0, v1.2.1].
    - Can only install one of: caouecs/laravel-lang[dev-laravel58, 3.0.62].
    - Can only install one of: caouecs/laravel-lang[dev-laravel58, 3.0.62].
    - Can only install one of: caouecs/laravel-lang[dev-laravel58, 3.0.62].
    - Conclusion: install caouecs/laravel-lang dev-laravel58
    - Installation request for caouecs/laravel-lang (locked at 3.0.62, required as ~3.0) -> satisfiable by caouecs/laravel-lang[3.0.62].

```

**Comment by andrey-helldar** [comment]
Hi!
https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v1.1.4

* Added hard binding to old versions (5.3-5.7)

This means that in the file composer.json you need to specify the version `^1.0`, or enter a command `composer require --dev andrey-helldar/laravel-lang-publisher:^1.0`

**Comment by andrey-helldar** [comment]
From readme.md:

Instead, you may of course manually update your require block and run `composer update` if you so choose:

```json
{
    "require-dev": {
        "andrey-helldar/laravel-lang-publisher": "^1.0"
    }
}
```

**Comment by jhm-ciberman** [comment]
Wow. That was super fast! I will try it when I reach home. Thanks a lot!

**Comment by andrey-helldar** [comment]
Well, I still do not sleep :-)

**Comment by jhm-ciberman** [comment]
I updated it now and it works like a charm :) 
Thanks!

**Comment by andrey-helldar** [comment]
You're welcome!

**Comment by andrey-helldar** [comment]
Now to install the package on Laravel version 5.3-5.7, the composer will correctly determine the allowed version of the 1st series (`^1.0`).

To install the package on Laravel 5.8 and higher, use version `^2.0`.

And see [compatibility table](https://github.com/andrey-helldar/laravel-lang-publisher#compatibility-table).
