### ISSUE TITLE
Laravel JetStream translate

### ISSUE THREAD

**Issue by MrFallen** [andrey-helldar/laravel-lang-publisher#71]
- Lang Publisher Version: last
- Laravel Version: last
- PHP Version: 7.4

### Description:
Hi guys. I was download Russian language for Laravel JetStream. How to accept this language?

### Steps To Reproduce:
https://github.com/andrey-helldar/laravel-lang-publisher#laravel-jetstream

**Comment by andrey-helldar** [comment]
Hi!
1. `composer update`
2. `php artisan lang:install --json ru`

Next calls,
`php artisan lang:update --json`

It is necessary to update the dependencies because one of the dependencies - `Laravel-Lang/lang` recently included translation for Jetstream.

**Comment by andrey-helldar** [comment]
Если на нашем, то мой пакет лишь устанавливает и обновляет зависимости. Сами файлы находятся в дочернем проекте. В нём то ли в 7.0.5, то ли в 7.0.6 опубликовали перевод Jetstream. Его перевод находится в json файлах, поэтому в своем проекте юзай ключ `--json` и будет счастье.

**Comment by MrFallen** [comment]
Doesn't works :(
![image](https://user-images.githubusercontent.com/5339386/95003748-b3800400-0625-11eb-80bd-985262b8f647.png)
![image](https://user-images.githubusercontent.com/5339386/95003761-d9a5a400-0625-11eb-9f4b-a7e1801e69d5.png)

**Comment by andrey-helldar** [comment]
What versions of the `andrey-helldar/laravel-lang-publisher` and `laravel-lang/lang` packages are installed?
I'm pretty sure the problem is with old packages.
Are you sure you called the `composer update` command?

**Comment by andrey-helldar** [comment]
My steps:
1. Install a fresh application (`laravel new test --jet`, ([see](https://jetstream.laravel.com/1.x/installation.html#installing-jetstream)))
2. Install a `andrey-helldar/laravel-lang-publisher` package: `composer require --dev andrey-helldar/laravel-lang-publisher`
3. Call the `php artisan lang:install --json ru` command
4. Change a `locale` option to `ru` in the `config/app.php` file.
4. It's all.

![image](https://user-images.githubusercontent.com/10347617/95012284-14b4d100-0640-11eb-824c-1516c33dea16.png)

![image](https://user-images.githubusercontent.com/10347617/95012286-1aaab200-0640-11eb-805f-a178015ec0d3.png)

![image](https://user-images.githubusercontent.com/10347617/95012299-2ac29180-0640-11eb-93cf-611554d7c952.png)

![image](https://user-images.githubusercontent.com/10347617/95012312-3910ad80-0640-11eb-9517-4b577b509866.png)

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/95012712-79bdf600-0643-11eb-9eed-b063b6f3722c.png)

![image](https://user-images.githubusercontent.com/10347617/95012723-8fcbb680-0643-11eb-8461-7dacf66a9200.png)

![image](https://user-images.githubusercontent.com/10347617/95012730-9e19d280-0643-11eb-93d2-0b6ea3f688d5.png)
